### ISSUE TITLE
SyntaxError controller.py

### ISSUE THREAD

**Issue by dckiller51** [guilhermgonzaga/rpi-cups-server#1]
Hello, I am trying to set up your script. I have an error when I run ./start.sh

```
File "./controller.py", line 51
    print(time.strftime('%d/%m/%y %H:%M:%S', lt), error, file=log)
                                                             ^
SyntaxError: invalid syntax
```

setting.json
```
{
	"io": {
		"in_file": "<used with python-daemon>",
		"log_file": "<always used>",
		"err_file": "<used with python-daemon>",
		"out_file": "<used with python-daemon>"
	},
	"printer": {
		"job_queue_cmd": ["lpstat", "-o", "<printer_name>"],
		"gpio_pin": "11",
		"control_pulse_duration_s": "5"
	}
}
```

I want to use your script to interface with homeassistant to control the printer socket

**Comment by guilhermgonzaga** [comment]
Hello.

It seems you are using Python 2, and the syntax I used is from Python 3 only.
The reason is that `print` changed from a statement to a function in the newer version.

The solution I recommend would be to import the function's definition (must be at the beginning):
```
from __future__ import print_function
```

You may alternatively do it the old way:
```
print >> log, time.strftime('%d/%m/%y %H:%M:%S', lt), error
```

Either way, I recommend you try to upgrade to Python 3 because I didn't test it on 2, so there might be more issues ahead.

**Comment by guilhermgonzaga** [comment]
Unrelated, but make sure to edit settings.json and fill in the keys that you use, such as `log_file` and `job_queue_cmd`.
Those `"<...>"` are just placeholders.

**Comment by dckiller51** [comment]
Thanks for feedback. I would do the test later. I finally set up the printer in a network.
But I think I will try again. Your script is interesting.
Thanks for taking time to respond to me
